spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/hyperlink_auth
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=qVWOU50WDNCEse0wGwh2QqhYnz+9FUCUq29bTHFvb5k=
jwt.expiration-ms=3600000

auth.bootstrap.admin.enabled=true
auth.bootstrap.admin.email=admin@example.com
auth.bootstrap.admin.password=Admin123!
auth.bootstrap.admin.full-name=Admin User